spring:
  datasource:
    url: jdbc:mysql://172.17.0.5:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: lintao_blog
  redis:
    host: 172.17.0.6
    password: root123
    port: 6379
  #上传文件配置
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 5MB
  mvc:
    servlet:
      path: /api
rocketmq:
  name-server: 172.17.0.2:9876
  producer:
    group: blog_group
server:
  port: 8888

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      table-prefix: ms_

#七牛云相关配置
qiniu:
  accessKey: bgsk1h-Cbkjx7ELwT2uQTRqpZc76JctxiT4QRwIR
  accessSecretKey: mJfYRoEmgsNbMNS2l5sqtUuSTitrcfnbzKvoaobQ
  url: http://rovo5kjl1.hn-bkt.clouddn.com/
  bucket: blog-image-zlt
mybatis:
  configuration:
    map-underscore-to-camel-case: true
