spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: lintao_blog
  redis:
    host: 43.136.59.155
    password: 168223

server:
  port: 8888

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      table-prefix: ms_